name: Develop CI2

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Digital Ocean and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: 2022
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/jdev.click/landing-pages
            git checkout main
            git fetch -p
            git pull origin main
            npm run build
<<<<<<< HEAD
            pm2 list
            pm2 restart 0
=======
            npm run start
>>>>>>> 3718cdc0cb750b176d3dc728adf4a740ac529106
